### ISSUE TITLE
Not adding to cart

### ISSUE THREAD

**Issue by sairit** [TreborNamor/Agressive-Bestbuy-Bot#11]
For some reason the bot is not adding the item to the cart, even though the item is in stock and I'm logged into my account.

**Comment by ProferoMalum** [comment]
Was running in to the same issue, but may have figured it out. I was using the Best Buy bot and used the URL of an item directly, but it would never add to card. However, if I used the search page, it would. So I think the bot does not work with direct product pages, only the search pages. Thankfully you can pare down the search page to the item you want pretty easily.

**Comment by TreborNamor** [comment]
> 
> 
> Was running in to the same issue, but may have figured it out. I was using the Best Buy bot and used the URL of an item directly, but it would never add to card. However, if I used the search page, it would. So I think the bot does not work with direct product pages, only the search pages. Thankfully you can pare down the search page to the item you want pretty easily.

yes, you are 100% correct. The bot will only work on URL product pages. If you are looking for a specific product only. Use the filters on the left side to narrow down your results.

**Comment by sairit** [comment]
Ok, Thank You!
