### ISSUE TITLE
Newegg bot won't sign in

### ISSUE THREAD

**Issue by pokejun2005** [TreborNamor/Agressive-Bestbuy-Bot#14]
Im pretty inexperienced so bare with me. So the bot will add to cart but when trying to input the username or password giving me this error

Button Found!: Add to cart 
Clicked Checkout Button in Cart.
Attempting Sign-In.
Could Not Login To Account With Password.
Trying Credit Card CVV Number.
Could Not Type CVV.
Could Not proceed with Checkout.
Order Placed!

**Comment by TreborNamor** [comment]
It could probably be that the bot had trouble logging in during checkout or another bot was able to purchase the product faster than this one.

**Comment by TreborNamor** [comment]
I do see this here from your text box

"Attempting Sign-In.
Could Not Login To Account With Password."
