### ISSUE TITLE
Log in issues with newegg

### ISSUE THREAD

**Issue by Civibes** [TreborNamor/Agressive-Bestbuy-Bot#19]
Everything works perfectly until the log in part comes in, itll just stay on the email section with my email in it but wouldn't go through after that.

**Comment by TreborNamor** [comment]
To help you auto login, close all firefox windows that the bot may have opened up. Open Firefox manually, and go to the newegg website. If you're logged in, log out. Then go to the sign in page and type in your login credentials. Newegg might ask for an auth code. As well, Firefox might ask you if you want to save your login and password. Click save if it does ask you. Now that you completed this you will be automatically logged in so the script will work.
