### ISSUE TITLE
Script won't add item to cart

### ISSUE THREAD

**Issue by yunusevsen** [TreborNamor/Agressive-Bestbuy-Bot#22]
Hello Robert!
I've watched your youtube videos and tried to run your script for the best buy bot. Unfortunately i don't know why the script won't add the item to the cart? I was wondering if you could help me out with that?

**Comment by TreborNamor** [comment]
I tested and updated the script right now. Hopefully this script works for you as well.

https://github.com/TreborNamor/Agressive-Bestbuy-Bot/blob/main/bestbuy.py

To test bot use this URL or a URL in the same format as this one.

https://www.bestbuy.com/site/searchpage.jsp?_dyncharset=UTF-8&id=pcat17071&iht=y&keys=keys&ks=960&list=n&qp=currentprice_facet%3DPrice~Less%20than%20%2425&sc=Global&st=hdmi&type=page&usc=All%20Categories

**Comment by yunusevsen** [comment]
Thanks! 
Going to check it out!

**Comment by yunusevsen** [comment]
Robert,
Is there a specific format URL you use? Because other bestbuy url's dont work for some reason

**Comment by yunusevsen** [comment]
So it seems to me that instead of using the product page. You go to the search bar and write whatever product you want. Then the script will choose the first item that pops up in the search list?
am i right?

**Comment by TreborNamor** [comment]
Yes that is correct. It was made specifically to scan multiple products to
find the first available product.  Whichever product first becomes
available, it will target that product.
