### ISSUE TITLE
F String

### ISSUE THREAD

**Issue by bmb2015** [TreborNamor/Agressive-Bestbuy-Bot#3]
Hi Trebor. I'm a noob. tried pycharm ce and followed your steps. I get 1 problem after analysis
Python version 2.7 does not support a 'F' prefix
How do i get around this? Thank you in advance. I did do some internet searching but no solution

**Comment by TreborNamor** [comment]
You just have to download python 3.9.1. You can find it here on this website for python.
 https://www.python.org/downloads/release/python-391/

**Comment by bmb2015** [comment]
Thank you. I am using a mac and i left python on and pointed the interpreter towards the user local python3, which was showing in the python preference. All good, its running. Thanks. Looking for Newegg one.
