### ISSUE TITLE
only refreshes about 5 times then stops with exit code 1

### ISSUE THREAD

**Issue by Gamerdude33** [TreborNamor/Agressive-Bestbuy-Bot#4]
so when I run this, after it reloads like 5 times it just stops and it says selenium.common.exceptions.WebDriverException: Message: Reached error page: about:neterror?e=dnsNotFound and this is probably a network error judging by what it says but my internet is working fine please help.
thanks

**Comment by kingmajesty02** [comment]
Were you able to fix your problem? I'm running into the same issue.

**Comment by Gamerdude33** [comment]
Yes I was it was because I didn’t have a secure internet connecting, I was using a proxy and it disconnected sometimes and interrupted the script so the script just stopped running and just put the error

**Comment by kingmajesty02** [comment]
hmmm I'm not using a proxy but I still run into this issue. Do you think it's because I leave it running for more than a few minutes or it's solely caused by poor internet connection? 

![image](https://user-images.githubusercontent.com/77119562/103943806-513d1080-50f8-11eb-9f2d-7002873d130f.png)

**Comment by Gamerdude33** [comment]
I had that issue also but many things can cause it I suggest that have ur connection that it doesn’t keep disconnecting on ur computer (that happened to me) because that showed up when I disconnected a few times
