### ISSUE TITLE
Doesn't add to cart when product is in stock

### ISSUE THREAD

**Issue by Gamerdude33** [TreborNamor/Agressive-Bestbuy-Bot#8]
A 3070 was in stock and it didn't add to cart it just kept refreshing over and over again

**Comment by Yuniecorn** [comment]
I can attest to this, I was unable to obtain a 3080 due to refreshing. I believe its due to Bestbuy's new queue system, where you click add to cart, and have to wait until the button  changes yellow again.

**Comment by TreborNamor** [comment]
Today, I made a new script that implies the queue system for Bestbuy. I haven't personally tried it but I believe the logic is spot on with what their queue system does. You can find it on GitHub down below. As well, I post the logic to the script too. Let me know if the queue system process is correct.

https://github.com/TreborNamor/Agressive-Bestbuy-Bot/blob/main/bestbuy-preorder.py

                # Queue System Logic. It is a 3 click process.
                try:
                    # Product Found, clicking "add to cart" button. (Page 1 - List of all RTX Products Page)
                    time.sleep(1)
                    driverWait(driver, 'css', '.add-to-cart-button') # this is the code that clicks add to cart.
                    timeSleep(2, driver)

                    # Entering Queue: Clicking "add to cart" 2nd time to enter queue. (Page 2 - Specific RTX Card Page)
                    preorderwait.until(EC.presence_of_element_located((By.CSS_SELECTOR, ".add-to-cart-button")))
                    driverWait(driver, 'css', '.add-to-cart-button') # this is the code that clicks add to cart.
                    time.sleep(5)

                    # In queue, waiting for "add to cart" button to turn clickable again. (page 2)
                    preorderwait.until(EC.presence_of_element_located((By.CSS_SELECTOR, ".add-to-cart-button"))) # this will wait until button is clickable.
                    time.sleep(2)
                    driverWait(driver, 'css', '.add-to-cart-button') # this is the code that clicks add to cart.
                    time.sleep(2)

                except (NoSuchElementException, TimeoutException):
                    pass

**Comment by Yuniecorn** [comment]
Thanks, I will update you when the next rtx 3080 drop occurs on bestbuy.
